### ISSUE TITLE
removing dependencies

### ISSUE THREAD

**Issue by anantshri** [n1nj4sec/mimipy#1]
I suppose one of the aim of doing this rewrite was to ensure person doesn't need to install gcore. however we are back to square one if the person has to install some pip package. It would be wonderful if the file is self contained. does everything on its own may be have vendor specific binaries pre compiled which can be picked based on what OS we are dealing with.

**Comment by n1nj4sec** [comment]
There are actually no dependencies, pip install is not mandatory, you can just copy the directory memorpy from https://github.com/n1nj4sec/memorpy/memorpy next to mimipy.py. I just didn't want to all write in one py file for readability but it can be packed or directly used from pupy (it's already merged in pupy unstable branch)

**Comment by anantshri** [comment]
awesome. Can i request this to be documented please may be just a 2 liners next to running standalone. Or better why not keep that in the same repo or as a git submodule so that we can pull all of them together. so from mimkatz prespective these are the dll's that needs to be present next to mimikatz.

**Comment by n1nj4sec** [comment]
since everyone is obsessed with self-contained python files (cc @huntergregal ), here you go
https://github.com/n1nj4sec/mimipy/packed/mimipy.py ;)

**Comment by anantshri** [comment]
Awesome. thanks for the awesome work @n1nj4sec highly appreciated.
